### ISSUE TITLE
World Map and Associated Line Chart

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/DSCI_532_group_201_natural_disasters#10]
Hi Team, 

I have created a new folder `charts` and added the initial version of the world map and associate line chart with interactive features in the file `world_map_line.html`. Please take a look when you have a chance and comment on this issue if you have any suggestions.

Thanks,
Jasmine

**Comment by jasmineqyj** [comment]
I've also included the source code for the world map and line chart in the `plots.ipynb` file under the `code` folder. Please let me know if you have any questions.

**Comment by singh-karanpal** [comment]
Thanks @jasmineqyj  I will merge this chart to app.py and upload it

**Comment by singh-karanpal** [comment]
If it is possible can we make one country selected by default in the world map? So that the associated line chart shows a clear line. (if this is possible)

**Comment by jasmineqyj** [comment]
@singh-karanpal I've set the `init` value for the click selection as `Canada` in my code. But when I save it to the `.html` file it's giving me that pink colour for all countries and thus the line chart doesn't make sense either. I will look into this issue and try if I could fix it.
