### ISSUE TITLE
Adding plots to app.py

### ISSUE THREAD

**Issue by singh-karanpal** [UBC-MDS/DSCI_532_group_201_natural_disasters#12]
Team,

I have created an app.py file. Please try to run it locally on your machines.
Also, send your charts as soon as possible. We need to host this app as well.

I will try to host this version, just to set up the workflow.

**Comment by jasmineqyj** [comment]
I've updated the map accordingly regarding issue #10. Could you please take a look and if you think the new initial chart is now better, add it to your `app.py`? Thanks.

**Comment by jasmineqyj** [comment]
@singh-karanpal do you think it's necessary to put the map and associated line chart to a separate page within the dashboard if this is possible (like adding a navigation bar or table of contents)? Having four graphs on the same page might be a little confusing for the users. Thanks.

**Comment by singh-karanpal** [comment]
@jasmineqyj Nice point! However, I feel all of these charts are associated and represent interlinked information. Users should be able to get all information by looking at just a single screen of the dashboard rather than going to and fro between multiple tabs. I think that might be a little annoying for users in this particular use case.

**Comment by sgauravm** [comment]
The app layout is finalized and deployed so closing this issue
