### ISSUE TITLE
Reflections on Natural Disaster Dash App

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/DSCI_532_group_201_natural_disasters#20]
Hi everyone, I've added few comments on our dash app in [`reflection.md`](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/blob/ffb16bbaee68215acfcd2b41605651a4916419eb/reflection.md). Please feel free to add on to it about how you think we can improve our app in the future. Thanks.

**Comment by sgauravm** [comment]
Added the new points
