### ISSUE TITLE
peer review from Dora & Miro

### ISSUE THREAD

**Issue by doraqmon** [UBC-MDS/DSCI_532_group_201_natural_disasters#27]
- The font size of the axis and title are too small
- Add some more dropdowns (e.g. country)
- Improve the layout
- Add the range of year to the slider bar
- Add blurb, footer
- All the titles should be more informative

Bar graph:
- the title should state clearly the time period of the data

Map:
- since the default is None, explanations should be added beside the graph

Historical Trend Plot:
- the y-axis log transform is very confusing

**Comment by sgauravm** [comment]
[Commit link for issue fixed](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/commit/5018e02a4c938aff7488f025606703ad21544d2e).
