### ISSUE TITLE
Review by Furqan

### ISSUE THREAD

**Issue by fkhan72** [UBC-MDS/DSCI_532_group_201_natural_disasters#28]
Overall the app looks good and it has lots of information from available. 
Minor things to change:
1) The 34M figure needs to be explained more
2) Try to replace the log values with actual numbers as reading negative log can be tricky
3) Check the zoom for the app

**Comment by jasmineqyj** [comment]
Closing this issue: @singh-karanpal has removed the 34M figure [here](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/pull/35) and @jasmineqyj has changed the log scale for the map [here](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/pull/32).
