### ISSUE TITLE
Comments about the App

### ISSUE THREAD

**Issue by vcuspinera** [UBC-MDS/DSCI_532_group_201_natural_disasters#29]
I really like the work you did for the app.

I just would say that maybe you could make some specific notes for to make it more under stable for the user:
- Maybe a footnote with the interpretation of the log scale of the last graph.
- Just make a comment to know that in the world map you should select a country.
- Make a comment that the map only shows the countries that have data.

Good luck!

**Comment by singh-karanpal** [comment]
Addressed footnote issue.
Addressed map issue, however, when we bind html with dash default conutry selection goes away. This is the issue with Dash app.

**Comment by singh-karanpal** [comment]
Closing this issue!
