### ISSUE TITLE
Peer review from Florence & Roc

### ISSUE THREAD

**Issue by fsywang** [UBC-MDS/DSCI_532_group_201_natural_disasters#30]
Here are some suggestions we came up: 
- Add some instructions or descriptions of the APP.
- Layout: probably add a background color.
- The second plot on the top: rename titles (Proportion of ...)
- Map: 
     - Probably set a default year and country instead of blank graphs
     - Map Log scale legend: Mention how the color is related to the plot since it is not that intuitive in log scale
     - For the slider, remove the _ in the legend

**Comment by jasmineqyj** [comment]
Closing this issue: @singh-karanpal has uploaded instructions to the dash [here](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/pull/35).
