### ISSUE TITLE
Summary of peer feedbacks

### ISSUE THREAD

**Issue by jasmineqyj** [UBC-MDS/DSCI_532_group_201_natural_disasters#31]
During this week's lab, we presented our dashboard to classmates and received some constructive feedbacks. After careful review, we prioritized the following implementations we could do to our dashboard to reflect their comments:

1. Add some instructions or descriptions of the APP
2. Log scale for change for 4th graph
3. Remove legend from country graph
4. _ part can be removed
5. Just make a comment to know that in the world map you should select a country.
6. Remove 341 Million
7. Check the zoom for the app
8. Change the font
9. Source footer

**Comment by singh-karanpal** [comment]
1. Add some instructions or descriptions of the APP - Done
6. Remove 341 Million - Done
7. Check the zoom for the app - Done
8. Source footer - Done

**Comment by sgauravm** [comment]
[Fixed font size of upper graphs](https://github.com/UBC-MDS/DSCI_532_group_201_natural_disasters/commit/5018e02a4c938aff7488f025606703ad21544d2e)

**Comment by sgauravm** [comment]
[](url)

**Comment by jasmineqyj** [comment]
1. Log scale for change for 4th graph - Done
2. Remove legend from country graph - Done
3. _ part can be removed - Done
4. Change the font - Done

**Comment by singh-karanpal** [comment]
Closing this issue!
