### ISSUE TITLE
Work Flow

### ISSUE THREAD

**Issue by sgauravm** [UBC-MDS/DSCI_532_group_201_natural_disasters#7]
A. Graphs:
  1. Bar chart - No interaction
  2. Line chart - ( Range selection)
  3. World Map - (Selecting each country, timeline)
  4. Death rate over the years for selected country.
  5. Drop down on death count

 B. Layout Creation:
  1. CSS and Dash

 C. Data Familiarity:
   1. global_data.csv
   2. earthquake_data.csv

 D. Work division:

  Karan and jack - CSS and Dash Part
  Gaurav - Bar chart, line chart, Drop Down on death count
  Jasmine - Map death rate

Notes:
1.Branch checkout: At the last stage deploy the branch(Only for deploying)
2.One person will be deployingperson deploying

**Comment by singh-karanpal** [comment]
@jacktan1 We can use the following resources for Dashboard Layout Designing. Just go through the first 2 videos on this channel.

1. [Dashboard with Dash](https://www.youtube.com/watch?v=yPSbJSblrvw)

**Comment by sgauravm** [comment]
The tasks identified in the documents were accomplished
